language: node_js

node_js:
  - "4.1"

before_script:
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g codecov
  - bower install
script:
  - grunt test

after_success:
  - codecov
