language: node_js

node_js:
  - "4.1"

before_install:
  - pip install codecov
after_success:
  - codecov

before_script:
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
script: grunt test